import type { ComponentType, CSSProperties } from "react"
import {
  Brain,
  Network,
  Component,
  Database,
  Cpu,
  Wifi,
  Search,
  Bot,
  Wand2,
  Boxes,
  Sparkles,
  SlidersHorizontal,
  ScanEye,
  Blend,
  Link2,
} from "lucide-react"
import { SiPython, SiC, SiNumpy, SiPandas, SiScikitlearn, SiGithub, SiJupyter, SiFigma, SiHuggingface, SiFastapi } from "react-icons/si"
import { FaJava, FaCode, FaAppStore } from "react-icons/fa"

export type IconType = ComponentType<{ className?: string; style?: CSSProperties }>

export interface Skill {
  name: string
  icon: IconType
  tagline: string
  description: string
  whyPoints: string[]
  related: string[]
  projects: string[]
  proficiency: number
  quote: string
  usedEverywhere?: boolean
}

export interface Shelf {
  id: string
  title: string
  skills: Skill[]
}

export const shelves: Shelf[] = [
  {
    id: "programming",
    title: "Programming",
    skills: [
      {
        name: "Python",
        icon: SiPython,
        tagline: "My primary programming language",
        description:
          "Python is my go-to language for building AI systems, data pipelines, backend services and automation. It's clean, powerful and incredibly versatile.",
        whyPoints: [
          "Easy to write and maintain",
          "Huge ecosystem for AI/ML",
          "Great for rapid prototyping",
          "Strong community support",
        ],
        related: ["FastAPI", "NumPy", "Pandas", "LangChain"],
        projects: ["DisasterVision", "NanoRAG Assistant", "Banking Data Assistant", "MemOrg AI", "Multimodal Airline Agent"],
        proficiency: 95,
        quote: "Python is not just a language, it's my creative playground.",
      },
      {
        name: "C",
        icon: SiC,
        tagline: "The language that taught me how computers think",
        description:
          "The language I learned core CS fundamentals on — memory, pointers, and how a computer actually executes instructions.",
        whyPoints: [
          "Deepened my understanding of memory & pointers",
          "Sharpened debugging fundamentals",
          "Foundation for systems-level thinking",
          "Still the fastest way to reason about performance",
        ],
        related: ["Data Structures & Algorithms", "Operating Systems"],
        projects: [],
        proficiency: 70,
        quote: "C taught me to respect what's happening under the hood.",
      },
      {
        name: "Java",
        icon: FaJava,
        tagline: "My go-to for structured, object-oriented code",
        description: "An object-oriented language I use for structured, strongly-typed programming and core CS coursework.",
        whyPoints: [
          "Strict typing keeps larger codebases sane",
          "Reinforces clean OOP design",
          "Common language for CS coursework",
          "Readable, disciplined syntax",
        ],
        related: ["OOP", "Data Structures & Algorithms"],
        projects: [],
        proficiency: 65,
        quote: "Java is where I learned to design before I code.",
      },
      {
        name: "SQL",
        icon: Database,
        tagline: "How I talk directly to data",
        description: "The language I use to query, shape, and reason about relational data.",
        whyPoints: [
          "Every real system eventually needs structured data",
          "Fast to query, filter, and reason about",
          "Pairs naturally with any backend",
          "The most direct way to ask a database a question",
        ],
        related: ["DBMS"],
        projects: [],
        proficiency: 75,
        quote: "SQL is the most honest conversation you can have with your data.",
      },
    ],
  },
  {
    id: "core-cs",
    title: "Core CS",
    skills: [
      {
        name: "Data Structures & Algorithms",
        icon: Network,
        tagline: "The foundation under every efficient system",
        description:
          "The foundation for writing efficient, scalable code — arrays, trees, graphs, and the algorithms that operate on them.",
        whyPoints: [
          "Makes AI systems fast, not just correct",
          "Sharpens problem-solving for interviews and real work",
          "Trees, graphs and hashing show up everywhere",
          "The skill that ages best",
        ],
        related: ["C", "Python", "OOP"],
        projects: [],
        proficiency: 80,
        quote: "Good architecture is just good data structures, scaled up.",
      },
      {
        name: "OOP",
        icon: Component,
        tagline: "How I keep growing codebases sane",
        description: "A way of structuring code around objects, state, and behavior rather than one long script.",
        whyPoints: [
          "Encapsulation keeps complexity contained",
          "Makes large codebases easier to reason about",
          "Encourages reusable, modular design",
          "Foundational to almost every language I use",
        ],
        related: ["Java", "Data Structures & Algorithms"],
        projects: [],
        proficiency: 78,
        quote: "OOP is how I stop a big project from becoming a big mess.",
      },
      {
        name: "DBMS",
        icon: Database,
        tagline: "The theory behind every schema I design",
        description: "The theory behind how data is stored, indexed, and kept consistent — beyond just writing queries.",
        whyPoints: [
          "Explains how data stays consistent under load",
          "Informs how I design schemas that hold up",
          "Goes beyond just writing queries",
          "Connects directly to how vector databases work too",
        ],
        related: ["SQL", "Vector Databases"],
        projects: [],
        proficiency: 72,
        quote: "Understanding DBMS internals is what makes my schemas hold up under real use.",
      },
      {
        name: "Operating Systems",
        icon: Cpu,
        tagline: "What's really happening beneath my code",
        description: "How processes, memory, and resources are actually managed beneath the applications I build.",
        whyPoints: [
          "Explains concurrency, memory, and scheduling limits",
          "Sharpens system-level debugging instincts",
          "Context for performance, not just correctness",
          "The layer every application quietly depends on",
        ],
        related: ["Computer Networks", "C"],
        projects: [],
        proficiency: 70,
        quote: "OS fundamentals are the difference between code that works and code that scales.",
      },
      {
        name: "Computer Networks",
        icon: Wifi,
        tagline: "How every app I build actually talks",
        description: "How data actually moves between the client, server, and everything in between.",
        whyPoints: [
          "Every project I ship is networked in some way",
          "Explains latency, APIs, and client-server design",
          "Makes debugging distributed systems less mysterious",
          "Context I lean on constantly while building backends",
        ],
        related: ["Operating Systems", "FastAPI"],
        projects: [],
        proficiency: 68,
        quote: "Every app is a conversation — networks are the language it's spoken in.",
      },
    ],
  },
  {
    id: "ai-ml",
    title: "AI Engineering",
    skills: [
      {
        name: "Machine Learning",
        icon: Brain,
        tagline: "The discipline behind every AI system I build",
        description: "The core discipline behind teaching systems to find patterns in data rather than following fixed rules.",
        whyPoints: [
          "The theory underneath RAG, CV, and agentic systems",
          "Helps me choose the right tool, not just the trendy one",
          "Turns \"it works\" into \"I understand why it works\"",
          "Central to how I approach every AI project",
        ],
        related: ["NumPy", "Pandas", "Scikit-Learn"],
        projects: ["DisasterVision", "NanoRAG Assistant", "MemOrg AI", "Xpert-Chroma"],
        proficiency: 88,
        quote: "Machine learning is how I teach systems to notice what I'd otherwise have to hard-code.",
      },
      {
        name: "NumPy",
        icon: SiNumpy,
        tagline: "The math engine behind my data work",
        description: "The library I reach for whenever I need fast, array-based numerical computation.",
        whyPoints: [
          "Fast, array-based computation for everything numerical",
          "The backbone underneath nearly every ML workflow",
          "Makes vector math actually tractable",
          "Quietly powers most of my preprocessing",
        ],
        related: ["Pandas", "Machine Learning"],
        projects: ["DisasterVision", "NanoRAG Assistant"],
        proficiency: 82,
        quote: "NumPy is where the real math of my projects actually happens.",
      },
      {
        name: "Pandas",
        icon: SiPandas,
        tagline: "How I clean and understand real-world data",
        description: "My go-to tool for cleaning, exploring, and reshaping structured data.",
        whyPoints: [
          "Turns messy raw data into something usable",
          "Fast exploration before anything touches a model",
          "My default tool for tabular data",
          "Makes data cleaning feel almost enjoyable",
        ],
        related: ["NumPy", "Machine Learning"],
        projects: ["DisasterVision"],
        proficiency: 82,
        quote: "Pandas is where messy data starts making sense.",
      },
      {
        name: "Scikit-Learn",
        icon: SiScikitlearn,
        tagline: "My go-to for classical, interpretable ML",
        description: "A toolkit of classical machine learning algorithms I use for straightforward, interpretable models.",
        whyPoints: [
          "Not every problem needs a neural network",
          "Great for fast, explainable baselines",
          "Clean API for experimenting quickly",
          "Still my first stop before reaching for anything heavier",
        ],
        related: ["Machine Learning", "NumPy"],
        projects: ["DisasterVision"],
        proficiency: 75,
        quote: "Sometimes the simplest model is the right one — Scikit-Learn is how I find out.",
      },
      {
        name: "RAG",
        icon: Search,
        tagline: "How I ground AI answers in real documents",
        description: "An architecture that grounds language models in real documents instead of relying on memory alone.",
        whyPoints: [
          "Lets an AI cite where its answer came from",
          "The architecture behind almost every assistant I've built",
          "Turns a language model into a genuine research tool",
          "The difference between an AI that guesses and one that knows",
        ],
        related: ["Vector Databases", "Embeddings", "LangChain"],
        projects: ["NanoRAG Assistant", "Banking Data Assistant", "DisasterVision", "MemOrg AI", "Xpert-Chroma"],
        proficiency: 92,
        quote: "RAG is how I stop AI from making things up.",
      },
      {
        name: "Agentic AI",
        icon: Bot,
        tagline: "Where AI stops chatting and starts doing",
        description: "Systems that don't just respond once, but reason, plan, and take multi-step actions toward a goal.",
        whyPoints: [
          "Multi-step reasoning instead of one-shot answers",
          "Combines retrieval, tools, and decision-making",
          "Where AI systems start to feel genuinely useful",
          "The direction I find most exciting in this field right now",
        ],
        related: ["RAG", "Prompt Engineering"],
        projects: ["Xpert-Chroma"],
        proficiency: 85,
        quote: "Agentic AI is the moment a chatbot becomes a colleague.",
      },
      {
        name: "Prompt Engineering",
        icon: Wand2,
        tagline: "The craft behind every reliable AI feature",
        description: "The craft of shaping inputs so a language model reliably produces the output you actually need.",
        whyPoints: [
          "The gap between a mediocre feature and a great one",
          "Makes LLM behavior consistent, not just impressive once",
          "Underlies every AI project I've shipped",
          "A skill that compounds fast with practice",
        ],
        related: ["RAG", "Agentic AI", "Fine-Tuning"],
        projects: ["DisasterVision", "NanoRAG Assistant", "MemOrg AI", "Multimodal Airline Agent", "Xpert-Chroma"],
        proficiency: 90,
        quote: "The right prompt is the difference between a demo and a product.",
      },
      {
        name: "Vector Databases",
        icon: Boxes,
        tagline: "How I make retrieval feel instant",
        description: "Storage systems built to search by meaning — finding the nearest matches in high-dimensional space.",
        whyPoints: [
          "Search by meaning, not just keywords",
          "Makes large document collections feel searchable in real time",
          "Core infrastructure behind every RAG system I build",
          "Where embeddings actually become useful",
        ],
        related: ["Embeddings", "RAG"],
        projects: ["DisasterVision", "MemOrg AI", "NanoRAG Assistant", "Xpert-Chroma"],
        proficiency: 85,
        quote: "Vector databases are what make \"search by meaning\" actually fast.",
      },
      {
        name: "Embeddings",
        icon: Sparkles,
        tagline: "How machines learn what things actually mean",
        description: "Numerical representations that capture the meaning of text or images, not just their raw form.",
        whyPoints: [
          "The bridge between raw text and real meaning",
          "Powers every semantic search I've built",
          "Makes retrieval smarter than exact keyword matching",
          "A concept I keep finding new uses for",
        ],
        related: ["Vector Databases", "RAG"],
        projects: ["MemOrg AI", "Xpert-Chroma", "NanoRAG Assistant", "DisasterVision"],
        proficiency: 85,
        quote: "Embeddings are how I teach a machine to understand meaning, not just words.",
      },
      {
        name: "Fine-Tuning",
        icon: SlidersHorizontal,
        tagline: "Adapting a model to actually fit the problem",
        description: "Adapting a pretrained model to a narrower task or domain by continuing its training on new data.",
        whyPoints: [
          "Pushes a general model to excel at a specific task",
          "Where I'm actively deepening my experience",
          "Bridges the gap between \"good enough\" and \"built for this\"",
          "An area I'm intentionally growing into",
        ],
        related: ["Transformers", "Prompt Engineering"],
        projects: [],
        proficiency: 55,
        quote: "Fine-tuning is teaching a model to stop generalizing and start specializing.",
      },
      {
        name: "Vision Language Models",
        icon: ScanEye,
        tagline: "Teaching AI to see and reason together",
        description: "Models that reason jointly over images and text, rather than treating them as separate problems.",
        whyPoints: [
          "Lets a system describe and reason about an image, not just classify it",
          "Core to how DisasterVision understands imagery",
          "Bridges computer vision and language in one model",
          "One of the most exciting frontiers in applied AI right now",
        ],
        related: ["Multimodal AI", "Transformers"],
        projects: ["DisasterVision"],
        proficiency: 80,
        quote: "VLMs are how I got AI to actually look at a photo and understand it.",
      },
      {
        name: "Multimodal AI",
        icon: Blend,
        tagline: "Meeting users where their data actually lives",
        description: "Systems that combine more than one type of input or output — text, image, audio — into one experience.",
        whyPoints: [
          "Real problems rarely come in a single format",
          "Combines text, image, and audio into one experience",
          "Makes AI assistants feel far more natural to use",
          "A direction I want to keep building deeper into",
        ],
        related: ["Vision Language Models", "Prompt Engineering"],
        projects: ["DisasterVision", "Multimodal Airline Agent"],
        proficiency: 78,
        quote: "The real world isn't just text — multimodal AI is how I build for that.",
      },
    ],
  },
  {
    id: "frameworks",
    title: "Frameworks",
    skills: [
      {
        name: "FastAPI",
        icon: SiFastapi,
        tagline: "How I ship AI backends fast",
        description: "A modern Python framework for building fast, typed APIs with minimal boilerplate.",
        whyPoints: [
          "Production-ready APIs with almost no boilerplate",
          "Typed, fast, and genuinely pleasant to work with",
          "My default choice for serving AI models",
          "Goes from prototype to backend in the same afternoon",
        ],
        related: ["Python", "RAG"],
        projects: ["DisasterVision", "NanoRAG Assistant", "Multimodal Airline Agent"],
        proficiency: 85,
        quote: "FastAPI is how an idea becomes a working API by the end of the day.",
      },
      {
        name: "LangChain",
        icon: Link2,
        tagline: "Wiring retrieval, memory, and tools together",
        description: "A framework for chaining together LLM calls, retrieval steps, and tools into a coherent pipeline.",
        whyPoints: [
          "Removes the boilerplate of chaining LLM calls by hand",
          "Structures multi-step reasoning cleanly",
          "My default when a pipeline needs more than one step",
          "Pairs naturally with any vector store I'm using",
        ],
        related: ["RAG", "Vector Databases", "Python"],
        projects: ["NanoRAG Assistant"],
        proficiency: 78,
        quote: "LangChain is the plumbing that lets an idea become a pipeline.",
      },
      {
        name: "Transformers",
        icon: SiHuggingface,
        tagline: "Direct access to state-of-the-art models",
        description: "A library giving direct access to state-of-the-art pretrained language and vision models.",
        whyPoints: [
          "Fastest path from \"I need a model for X\" to a working prototype",
          "Access to pretrained language and vision models",
          "Backbone of nearly every model I fine-tune or adapt",
          "Huge, well-documented ecosystem to build on",
        ],
        related: ["Vision Language Models", "Fine-Tuning", "Machine Learning"],
        projects: ["DisasterVision"],
        proficiency: 80,
        quote: "Transformers put frontier models one import away.",
      },
      {
        name: "Gradio",
        icon: FaAppStore,
        tagline: "Turning a script into a demo people can touch",
        description: "A library for turning a Python function into a shareable, interactive web interface in minutes.",
        whyPoints: [
          "Working demo in minutes, no frontend required",
          "Great for putting an AI prototype in front of real people",
          "My go-to for chat and voice interface demos",
          "Removes the excuse of \"I'll build a UI for it later\"",
        ],
        related: ["Python", "FastAPI"],
        projects: ["FlightAI Assistant", "Multimodal Airline Agent", "NanoRAG Assistant"],
        proficiency: 75,
        quote: "Gradio is how a Python function becomes something people can actually try.",
      },
      {
        name: "BeautifulSoup",
        icon: FaCode,
        tagline: "Turning a messy webpage into usable data",
        description: "A library for parsing and extracting information out of HTML pages.",
        whyPoints: [
          "Simplest way to parse HTML into structured data",
          "Feeds real content into downstream AI generation",
          "Reliable for straightforward scraping tasks",
          "Still my first reach for a quick scraping job",
        ],
        related: ["Python"],
        projects: ["Marketing Brochure AI"],
        proficiency: 68,
        quote: "BeautifulSoup is how the open web becomes structured data.",
      },
    ],
  },
  {
    id: "tools",
    title: "Developer Tools",
    skills: [
      {
        name: "VS Code",
        icon: FaCode,
        tagline: "Where everything I build actually gets written",
        description: "My primary editor for everything I write, from quick scripts to full applications.",
        whyPoints: [
          "Extension ecosystem covers nearly everything I need",
          "Debugging tools that are hard to beat",
          "Used across every project in this portfolio",
          "Feels like home after years of daily use",
        ],
        related: ["GitHub"],
        projects: [],
        proficiency: 95,
        quote: "VS Code is less a tool and more where I actually think in code.",
        usedEverywhere: true,
      },
      {
        name: "GitHub",
        icon: SiGithub,
        tagline: "Where every project gets versioned and shared",
        description: "Where I version, host, and collaborate on every project I build.",
        whyPoints: [
          "My safety net for tracking every change",
          "Where I showcase every finished project",
          "Central to how I collaborate on code",
          "Used across every project in this portfolio",
        ],
        related: ["VS Code"],
        projects: [],
        proficiency: 90,
        quote: "GitHub is both my history and my portfolio, all in one place.",
        usedEverywhere: true,
      },
      {
        name: "Jupyter Notebook",
        icon: SiJupyter,
        tagline: "Where I think out loud through data",
        description: "An interactive environment for exploring data and iterating on models step by step.",
        whyPoints: [
          "See output after every cell instead of a full re-run",
          "My default for data exploration and model prototyping",
          "Makes iterating on an idea genuinely fast",
          "Where most of my experiments actually start",
        ],
        related: ["Python", "Pandas", "NumPy"],
        projects: ["DisasterVision", "NanoRAG Assistant"],
        proficiency: 85,
        quote: "Jupyter is where a rough idea turns into a working experiment.",
      },
      {
        name: "Figma",
        icon: SiFigma,
        tagline: "Where an interface exists before any code does",
        description: "A collaborative design tool I use for mocking up interfaces before writing any code.",
        whyPoints: [
          "Sketching the UI first saves real rebuild time later",
          "Helps me think through layout before committing to code",
          "Useful for quickly sharing a visual idea",
          "A tool I reach for before any frontend work begins",
        ],
        related: [],
        projects: [],
        proficiency: 60,
        quote: "Figma is where I make my mistakes before they cost me any code.",
      },
    ],
  },
]
